name: Enviar predicción del tiempo a Telegram

on:
  schedule:
    - cron: '0 18 * * *'  # Ejecuta todos los días a las 07:00 UTC (ajusta según tu zona horaria)
  workflow_dispatch:  

jobs:
  send_weather_forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        env:
          AEMET_KEY: ${{ secrets.AEMET_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID2: ${{ secrets.TELEGRAM_CHAT_ID2 }}
        run: python app.py
